// <auto-generated />
using System;
using ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325161937_AddJiraTicketFields")]
    partial class AddJiraTicketFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiService.Models.PipelineFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .HasColumnType("text");

                    b.Property<bool>("AutoHandled")
                        .HasColumnType("boolean");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("JiraCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("JiraTicketId")
                        .HasColumnType("text");

                    b.Property<string>("JiraTicketUrl")
                        .HasColumnType("text");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RetryAttempted")
                        .HasColumnType("boolean");

                    b.Property<string>("RootCause")
                        .HasColumnType("text");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedFix")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PipelineFailures");
                });
#pragma warning restore 612, 618
        }
    }
}
